// Code generated by github.com/995933447/structfieldconstgen. DO NOT EDIT.
package enum

const (
	FieldId = "id"
	FieldCreatedAt = "created_at"
	FieldUpdatedAt = "updated_at"
	FieldDeletedAt = "deleted_at"
	FieldName = "name"
	FieldImage = "image"
	FieldSort = "sort"
	FieldRemark = "remark"
	FieldBuddhaId = "buddha_id"
	FieldUid = "uid"
	FieldLastWatchedAt = "last_watched_at"
	FieldPhone = "phone"
	FieldPassword = "password"
)